### ISSUE TITLE
Elmo fault is not latched

### ISSUE THREAD

**Issue by d-loret** [nasa-jpl/jsd#33]
The fault reported by the Elmo motor controller is not latched in the EGD driver because the fault is i[mmediately reset after printing to screen the fault code](https://github.com/nasa-jpl/jsd/blob/master/src/jsd_egd.c#L1307-L1320).

This can make detecting errors fragile because the error code is reported in the state only once. If the client code misses that particular frame, the error will not be detected.

**Comment by d-loret** [comment]
@alex-brinkman, can I get more details about the rationale for not latching Elmo errors at the driver level? It seems to me that client code could lose this information if it's only transmitted once, and some of these errors represent critical failure of the drive (e.g. `JSD_EGD_FAULT_FEEBACK_LOSS`, `JSD_EGD_FAULT_CPU_FATAL_EXCEPTION`, etc.).

The complication of changing this is that the driver's behavior is to always try to get into Operation Enabled. We could try latching at the Fastcat level, but ideally we should handle it at the JSD driver level.

**Comment by alex-brinkman** [comment]
There's not much  rationale for immediately clearing the fault and trying to return the JSD EGD state machine to operational - it was most likely due to proof-of-concept code propagating until now. 

If you have good reason for changing it, I support modifications. Given how long JSD EGDs have been been running this way, I'd ask that you implement it by creating an optional configuration parameter that defaults to this behavior and can be used to change the function as you need for your application. 

For fault reporting, the EMCY codes will go away after they are popped so I recommend introducing a new feature to save a circular buffer of these events with timestamps if you want to save fault codes for async access by applications. LMK if that does not make sense to you.

**Comment by alex-brinkman** [comment]
in the modifications contained in #46, the fault code data is saved to the device state until a reset is issued and the drive returns back to OPERATION_ENABLED. If you are satisfied with this behavior we can consider this issue closed when that PR is concluded.
