### ISSUE TITLE
Multiple product codes

### ISSUE THREAD

**Issue by MartynStaalsen** [nasa-jpl/jsd#94]
I've encountered an issue where different physical instances of the same Beckhoff slice have slightly different product codes because they're different revisions. Despite the revision difference, both pieces of should be able to use the same jsd interface. Unfortunately, jsd  seems to be built around the assumption that there's exactly 1 product code per piece of hardware. Any recommendations on how to accomodate multiple product codes per interface without just copying and pasting the driver with and renaming everything?

**Comment by d-loret** [comment]
@MartynStaalsen, you could try something similar to what we did with the driver for Elmo Platinum motor controllers. There are two models of the drive with [different codes](https://github.com/nasa-jpl/jsd/blob/master/src/jsd_epd_types.h#L11-L17) but the same basic functionality that we support.
So instead of directly referring to the product code, a helper function was written to check whether the [product code is compatible](https://github.com/nasa-jpl/jsd/blob/master/src/jsd_epd.h#L101-L108).
